### ISSUE TITLE
Workspaces Summary Endpoint Data Out of Date

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#1013]
We have had reports that the Workspaces Summary endpoint is not supplying up to date data. This is a high priority bug if confirmed. Thanks to @henryzhang00 for the report!

**Comment by zipy124** [comment]
If the header is correct we haven't updated the cache in 2 days??

**Comment by ChristopherHammond13** [comment]
If that's the case then I need to sort this ASAP because the only thing worse than an API that's down is an API that's supplying faulty data

**Comment by zipy124** [comment]
Are there logs for the cronbox that runs cache.py. It should update the header at the bottom so that indicates we aren't reaching that line, or the commands just isn't running at all.

**Comment by ChristopherHammond13** [comment]
Yeah I checked the cron box logs, and found that some code was tripping over itself so I updated the crontab to give the full cache more breathing room the 2am cache time.
