### ISSUE TITLE
No bookings found

### ISSUE THREAD

**Issue by anushks** [uclapi/uclapi#102]
**Example:** Cruciform Lecture Theatre 1 **Date:** 13/09/2017
As you can see there is a booking present today:
![image](https://user-images.githubusercontent.com/23053319/30383062-aec2c806-9898-11e7-96ec-d8c78d1966ef.png)

If using your website to check, the following is displayed (no bookings found):
![image](https://user-images.githubusercontent.com/23053319/30383128-d8d38554-9898-11e7-985a-b3705adaa00c.png)

Similarly, if I run a request using my own token, for the specified date, the same problem arises.

**Comment by ChristopherHammond13** [comment]
I'm bringing production up to date now with the `LIVE-17-18` set which should move us on to the new year's data.

**Comment by ChristopherHammond13** [comment]
Okay, update: this should be working now. @anushks could you please test and let me know if it's ok now? Thanks so much, and apologies! :)

**Comment by anushks** [comment]
Yep, just tested it and it works @ChristopherHammond13, thanks!
