### ISSUE TITLE
Unify Locking

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#1067]
At the moment there are two `gencache` locks: one for roombookings, and one for timetable. We should unify this such that we have one lock shared between the two, so that we can guarantee correctness when we combine data from the two. This will be useful in #1064.

**Comment by zipy124** [comment]
While i'm migrating stuff away from oracle i may aswell do this

**Comment by ChristopherHammond13** [comment]
Will be resolved by #1064

**Comment by ChristopherHammond13** [comment]
This was resolved by #1064
