### ISSUE TITLE
JS Demo code on homepage does not work

### ISSUE THREAD

**Issue by JasonEtco** [uclapi/uclapi#112]
Hello 👋 The JS in your demo code wouldn't actually work, `fetch` expects either a `string` or an `object` as the first argument; in this case, you give it a couple of strings as separate arguments. I guess you mean for them to be an array and join them?

https://github.com/uclapi/uclapi/blob/c0edf4bb160a561fdb149f8b5e7293cae69b3ec2/frontend/src/react/components/getStarted/Demo.jsx#L406-L416

cc @wilhelmklopp because hey how are you

**Comment by ChristopherHammond13** [comment]
Hey, @JasonEtco, thanks for noticing this! @anirudhpillai is this something we can fix?

**Comment by ChristopherHammond13** [comment]
Just as an update on this, it is my understanding that #111 will fix this issue when it's completed.

**Comment by ChristopherHammond13** [comment]
This should now be resolved in Staging and will be coming to a prod near you this afternoon! :tada:

**Comment by ChristopherHammond13** [comment]
@anirudhpillai @wilhelmklopp is this all sorted now?

**Comment by ChristopherHammond13** [comment]
This has been our longest open issue ever BUT we have finally got a resolution thanks to @anirudhpillai!

#567 will close this issue.
