### ISSUE TITLE
Add date filter to timetable API

### ISSUE THREAD

**Issue by LeoMcA** [uclapi/uclapi#122]
It'd be incredibly useful to be able to filter the timetable API by date.

This could be implemented one of two ways:

**With a `date` parameter**:
e.g. querying `/timetable/personal?date=2018-01-23` would return:
```
{
  "timetable": {
    "2018-01-23": [...]
  }
}
```

**With `start_date` and `end_date` parameters**:
e.g. querying `/timetable/personal?start_date=2018-01-23&end_date=2018-01-25` would return:
```
{
  "timetable": {
    "2018-01-23": [...],
    "2018-01-24": [...],
    "2018-01-25": [...],
  }
}
```

I'd favour the first approach, but mostly because it's what I'd find most useful at the moment in the hackathon ;)

**Comment by ChristopherHammond13** [comment]
This has been resolved by #125! You can use the `date_filter` query parameter to specify a date (e.g. `&date_filter=2017-10-09` for 9th October 2017's events). If there are no events it'll return an empty list.
