### ISSUE TITLE
Timetable by module returns {ok: true} for nonexistent classes

### ISSUE THREAD

**Issue by achen04** [uclapi/uclapi#123]
By putting in a random nonexistent module, API returns `{ ok: true, timetable: {} }` where you would expect it to return `{ok: false}` on modules that cannot be found in the database.

**Comment by ChristopherHammond13** [comment]
Good shout. Would you like us to reject the entire set of courses if one of them doesn't exist, or return the courses that are recognised?

**Comment by achen04** [comment]
I think rejecting the entire set of courses would be better because if just the recognized courses are returned, we would have to parse through the JSON to check if all inputed courses are there. 

Rejecting the entire set would save that check since the check is necessary to notify the client that the input is wrong.

**Comment by ChristopherHammond13** [comment]
This will be resolved by #127

**Comment by ChristopherHammond13** [comment]
Now resolved and will be in production very soon :)
