### ISSUE TITLE
Return 400 HTTP status code on missing params

### ISSUE THREAD

**Issue by cbetta** [uclapi/uclapi#129]
The current API returns an HTTP status code of 405 when a request parameter is missing. This seems to be incorrect. I quote from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405):

> The HTTP 405 Method Not Allowed response status code indicates that the request method is known by the server but has been disabled and cannot be used. The two mandatory methods, GET and HEAD, must never be disabled and should not return this error code.

In other words, it's exclusively used to signal that the wrong HTTP verb (GET, POST, etc) was used for the request. In this case, a HTTP status code of 400 seems more correct.

**Comment by ChristopherHammond13** [comment]
Thanks for the feedback, @cbetta! Which endpoint(s) have you noticed this on? In most (ideally all!) cases, we have specified a 400 status code when there are missing or incorrect parameters so it's possible that some have slipped through the net.

**Comment by cbetta** [comment]
@ChristopherHammond13 I know you've specified 400 but it's returning a 405 for me.

I get a 405 on both the `/search/people` endpoint and the `/roombookings/equipment` endpoint.

```sh
> curl -I https://uclapi.com/roombookings/equipment?token\=uclapi-1234567XXXX
HTTP/1.1 405 Method Not Allowed
```

**Comment by cbetta** [comment]
Ignore me. I forget that `-I` does not just debug the response header, but actually makes a `HEAD` request (rather than a `GET` one). You might want to consider responding to `HEAD` requests as a `GET` request as well.

**Comment by cbetta** [comment]
I meant to use `-i`. My bad.

**Comment by ChristopherHammond13** [comment]
No problem :)
