### ISSUE TITLE
UCL Assistant page

### ISSUE THREAD

**Issue by hueyy** [uclapi/uclapi#1332]
uclapi.com should showcase UCL Assistant in some way. I'm thinking a button on the first section (beside the Dashboard & Docs links) and a section of its own somewhere on the page.

This should have screenshots, features, and enticing marketing copy.

**Comment by zipy124** [comment]
We should also add this to the marketplace screen probably?

**Comment by hueyy** [comment]
Oh yeah I forgot it existed. Yeah, then we'll finally have a live app there.
