### ISSUE TITLE
[Feature Request] Expose all Shibboleth UCL Intranet Groups via OAuth

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#1389]
**Is your feature request related to a problem? Please describe.**
It is not possible to determine which faculty a user is in, or whather they have special access (e.g. to do the Bloomsbury Theatre builings), each of which places them in a new UCL Intranet Group.

Without this feature in place it is not possible to migrate EngHub from raw Shibboleth to UCL API OAuth.

**Describe the solution you'd like**
A list of each UCL Intranet Group should be provided via the `/user/data` endpoint.

**Describe alternatives you've considered (optional)**
Parsing this data on the API's side and providing metadata (such as the Faculty a user is in) instead of a raw list of groups. This might be hard to do without a lot of help from ISD though.

**Comment by zipy124** [comment]
Does the shibboleth response give us all the group information?
