### ISSUE TITLE
Oauth page clean-up

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#1407]
![image](https://user-images.githubusercontent.com/6523121/59549628-e9adf600-8f92-11e9-97bf-8c3f228e0736.png)

The oauth page probably needs a bit of work aesthetically, and I'm not sure how to test it locally. I did try creating an app and authenticating with it, but it didn't seem to appear on my oauth settings page.

I suggest we merge this, but hide the oauth page from the navbar until we clean it up a bit.

_Originally posted by @hueyy in https://github.com/uclapi/uclapi/pull/1132#issuecomment-502351583_

**Comment by TuxedoFish** [comment]
Can you double check the oauth token is showing up in datagrip because it works on my local machine?
