### ISSUE TITLE
[BUG] FAQ error in rendering

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#1460]
**Describe the bug**
Text overflows the line

**To Reproduce**
Scroll down on staging.ninja

**Expected behavior**
Box expands if text wraps a line

**Screenshots**
![Screenshot from 2019-07-21 21-13-33](https://user-images.githubusercontent.com/6547350/61596508-91ef5400-abfc-11e9-9f9b-2e8d9de1b288.png)

**Comment by TuxedoFish** [comment]
Fixed, was down to height being explicitely set in one of the css files
