### ISSUE TITLE
Refactor the frontend

### ISSUE THREAD

**Issue by TuxedoFish** [uclapi/uclapi#1482]
I'm always frustrated when trying to navigate the frontend files and trying to extend upon the current form of the website

I want everything to be standardised across the pages in the website preventing duplicated code and solutions wasting time.

Keeping each page compartmentalised is another solution although it holds us back I think.

NO AESTHETIC CHANGE FROM MASTER, Just looking to organise the components in an easier to extend manner!

**Comment by hueyy** [comment]
Definitely. The lack of standard components is really a shame.

**Comment by Feverfew** [comment]
Django templates can help here...

**Comment by TuxedoFish** [comment]
#1520 <3

**Comment by hueyy** [comment]
Resolved by #1520
