### ISSUE TITLE
[BUG] Studyspaces includes testing data

### ISSUE THREAD

**Issue by hueyy** [uclapi/uclapi#1531]
**Describe the bug**
* The UCL Institute of Neurology is labelled `"UCL Institute of Neurology` (with the double quotes prepended)
* A testing version of the Graduate Hub studyspace labelled `Graduate Hub - RP Dev Testing` is being served

**Screenshots**
<img src="https://user-images.githubusercontent.com/6523121/63226763-cca2d700-c210-11e9-8b1a-f5b61e7c01b8.jpg" width="200" />

**Additional context**
I suspect the first issue may be at the OccupEye side

**Comment by Feverfew** [comment]
Yeah we can sort that out. Regarding the quotes, might be easy enough for me just to strip double quotes...

**Comment by hueyy** [comment]
Since they appear to add workspaces for testing semi-regularly and without any warning, we might want to build in some simple filters, e.g. exclude studyspaces with names that include the word`Testing`.

**Comment by hueyy** [comment]
https://en.wikipedia.org/wiki/Scunthorpe_problem
