### ISSUE TITLE
[Feature Request] Analytics

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#1636]
**Is your feature request related to a problem? Please describe.**
We used to use Keen for analytics such as new OAuth users signing up. However our subscription (or free trial?) ran out. Ideally we'd like some stats without having to ssh into prod.

**Describe the solution you'd like**
Enabling Django admin would fit the bill easily. We just have to consider how to sort out the login.

**Describe alternatives you've considered (optional)**
Re-enabling Keen?

**Comment by zipy124** [comment]
I'm going to suggest building our own with grafana? Free and self-hosted which we have the spare server capacity to do.

**Comment by Feverfew** [comment]
Analytics is a bit broad... let me refine:

1. How many tokens are being actively used.
2. Who are our most active users?
3. Which are our most active endpoints.
4. How many apps have received permission for personal data in OAuth?
5. whatever else that we already store in the database but can't easily see.

What is out of scope, is stuff like server load, that's all on AWS. Analytics on UCL Assistant is already being handled by Huey. The stuff I listed above is all sitting on our DB, and Django Admin is extensible enough that we can get it all on there. It's simple, and isn't hard to maintain. I'll let Zak comment on what grafana, as I have no idea what it does, but I can personally vouch for the simplicity of use in using Django Admin. It's easy to test, easy to maintain and I know it well enough that I can help work on it/review patches.
