### ISSUE TITLE
[BUG] Completely inaccurate Workspace data

### ISSUE THREAD

**Issue by henryz00** [uclapi/uclapi#1783]
**Describe the bug**
Workspace data either not up to date or inaccurate compared to UCL Go app. It is also impossible to get 90% full in every Library at 1 am (at least not during exam time).

**To Reproduce**
In every app uses UCL API workspace data.

**Expected behaviour**
Data should be correct and consistent with UCL Go app.

**Screenshots**
<img width="1244" alt="WX20191105-005205@2x" src="https://user-images.githubusercontent.com/20445029/68170144-88e58100-ff66-11e9-8c5a-be2a44eaeca6.png">
Left: UCL Go (Assume correct data); Middle: UCLCSSA (our app); Right: UCL Assitant.

<img width="801" alt="WX20191105-005056@2x" src="https://user-images.githubusercontent.com/20445029/68170157-90a52580-ff66-11e9-84cb-f866de947569.png">
Left: UCL Go (Assume correct data); Right: UCL Assitant.

**Additional context**
Has been happening for at least a week.

**Comment by Feverfew** [comment]
Hi, thanks for reporting the bug. We've had our account for workspaces revoked unexpectedly...

We're getting in contact with the supplier ASAP to restore access and I'll close this issue once this is done.

**Comment by henryz00** [comment]
Any updates on this?

**Comment by zipy124** [comment]
@henryz00 This has now been fixed.
