### ISSUE TITLE
[Feature Request] Add UCLCSSA to marketplace

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#1821]
This is an app similar to UCL Assistant for we-chat I think. The link can be found here https://mp.weixin.qq.com/s/ndkYgEFwlATvIIcHONG2uA

**Comment by henryz00** [comment]
Thanks for raising this, very much appreciated! 

UCLCSSA is indeed like UCL Assitant but a web app embedded in WeChat. It includes most of the functions UCL API provides. although mainly target at Chinese students at UCL, it can be migrated to standalone web apps in the future. 

We have our official website here: https://uclcssa.cn/
Timetable app demo: https://uclcssa.cn/timetable/?id=demo

**Comment by TuxedoFish** [comment]
Hey @henryz00 just saw this, I have opened a branch feature/update-marketplace . I will attach some photos of what it looks like and if you have anything you want me to change or how you want to do the description I am happy to change it to what you want. I was working with a google translate of the we chat page so the description isn't the best at the moment!

![image](https://user-images.githubusercontent.com/3999881/68932663-fb3a3a80-078a-11ea-9c61-6a43a6c71f85.png)

![screencapture-localhost-8000-marketplace-uclcssa-2019-11-15-09_33_43](https://user-images.githubusercontent.com/3999881/68932697-0d1bdd80-078b-11ea-912b-8c2bd686d149.png)

I will add a link to your website and demo as well

**Comment by henryz00** [comment]
Thank you!!
It would be totally okay to use the demo at the hackathon!

**Comment by henryz00** [comment]
I think the description is actually quite accurate 😂

Here are some newer screenshots if you can swap them with the old ones would be great!
From the newer WeChat mp article: https://mp.weixin.qq.com/s/uij8Z05hB7aKJm0Ln0SI8g

![image](https://user-images.githubusercontent.com/20445029/68951565-4453b400-07b6-11ea-951a-14b98181c67c.png)
![image](https://user-images.githubusercontent.com/20445029/68951914-e07dbb00-07b6-11ea-8bdb-51e0cc7038ba.png)
![image](https://user-images.githubusercontent.com/20445029/68951828-ba581b00-07b6-11ea-8e1c-8c88f7e5f6f0.png)
![image](https://user-images.githubusercontent.com/20445029/68951932-e7a4c900-07b6-11ea-8cbf-2121ec5911e0.png)
![image](https://user-images.githubusercontent.com/20445029/68951953-ed021380-07b6-11ea-8692-971d2ff92cd1.png)

And also a youtube video if applicable 😀
https://www.youtube.com/watch?v=0Q3WJDENFAM

Thanks again! The new site looks awesome!!

**Comment by TuxedoFish** [comment]
@henryz00 Cheers, the app looks so awesome very aesthetic!! Ill add those screenshots, thanks man means alot we put a lot of effort into it :D Ill add that video into the description as well!

**Comment by TuxedoFish** [comment]
@henryz00 Let me know if you are happy with this!
![screencapture-localhost-8000-marketplace-uclcssa-2019-11-18-20_30_55](https://user-images.githubusercontent.com/3999881/69091519-619cb280-0a42-11ea-9896-c2a35e31cb92.png)

**Comment by henryz00** [comment]
This looks Perfect! Thanks a lot!! looking forward to the new site.

**Comment by TuxedoFish** [comment]
@henryz00 Awesome!! Thanks man should be a big improvment!
