### ISSUE TITLE
[BUG] Highlighting marketplace icon for CSSA has white square shown on hover

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#1846]
Give it a transparent background, or othewise fix.
![Screenshot from 2019-11-20 23-32-47](https://user-images.githubusercontent.com/6547350/69287444-2b9c3180-0bee-11ea-8ebf-7b97311a7c51.png)

**Comment by henryz00** [comment]
I have a few alternative logos:
![qr2](https://user-images.githubusercontent.com/20445029/69369896-c64f4b80-0c94-11ea-9d8a-d6134cc90338.png)
↑QR code with circular background 

![qr](https://user-images.githubusercontent.com/20445029/69369902-c94a3c00-0c94-11ea-9089-ed217bc543c1.png)
↑QR code with transparent background  (but might not be visible on the dark background)

![new_logo](https://user-images.githubusercontent.com/20445029/69369890-c3ecf180-0c94-11ea-9b31-4399427295f8.png)
↑logo with transparent background (if chosen to go with this one, could you please add the QR code with the white background on the detail page? Thanks!)

**Comment by zipy124** [comment]
Fixed and present on https://staging.ninja, Promoting to production.
