### ISSUE TITLE
Document date_filter parameter for timetable endpoint

### ISSUE THREAD

**Issue by hueyy** [uclapi/uclapi#1931]
**Is your feature request related to a problem? Please describe.**

The /timetable/personal endpoint accepts an undocumented `date_filter` query parameter in ISO 8601 format, i.e. YYYY-MM-DD

**Describe the solution you'd like**

Document this in uclapi.com/docs

**Comment by Feverfew** [comment]
Depends on #1934 

Basically, if people start to split their requests into smaller dates than 1 year, then it will actually affect our performance worse. Once the above issue is resolved then we can actually publicise this. I'll add this onto my ever-growing TODO.

**Comment by zipy124** [comment]
Since #1934 has been indicated as less important due to caching, this can now be done.
