### ISSUE TITLE
[BUG] Timetable Filtering

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#1934]
**Describe the bug**
Currently we only filter the timetable by date in Python after the following two steps, which happens to be at the worst possible time.
1. We generate the whole timetable in SQL.
2. We then serialise it into JSON with Python.

This would be slightly less criminal if we did it between steps 1 and 2, but it's currently completely unacceptable in terms of performance.

**Expected behavior**
Do filtering in the DB, like a sane, normal person.

**Comment by zipy124** [comment]
Since we cache the timetable does it actually matter too much?

**Comment by Feverfew** [comment]
> Since we cache the timetable does it actually matter too much?

Yes it isn't as big as an issue as is implied, but we should do the filtering on the DB side IMO, (but then we have to be careful with the cache!)
