### ISSUE TITLE
timetable/data/departments endpoint returns 500 error

### ISSUE THREAD

**Issue by keelanfh** [uclapi/uclapi#194]
The timetable/data/departments endpoint is currently returning a 500 error on any request.

I know it's not a documented endpoint, but it would be nice if it worked :)

It looks to me like the problem is line 85 below - `rate_limiting_data` is being passed as an argument to `append`. 

https://github.com/uclapi/uclapi/blob/cfd6753ae3d979bbe53573dad68babc2de19e04d/backend/uclapi/timetable/views.py#L82-L85

Removing that and replacing with this:
```python
depts["departments"].append({ 
"department_id": dept.deptid, 
"name": dept.name}) 
```
should fix it, though I don't have the whole API setup installed, so I can't be sure.

**Comment by ChristopherHammond13** [comment]
Sorry, just saw this! That looks right to me.

We should have this endpoint documented at some point (I think I actually wrote it up before; some of my work got lost when we moved to a new docs setup).
