### ISSUE TITLE
[Feature Request] API exposing data about individual apps

### ISSUE THREAD

**Issue by hueyy** [uclapi/uclapi#2038]
**Is your feature request related to a problem? Please describe.**

* Display number of requests, authorisations, etc.

**Describe the solution you'd like**

* Expose an API providing this
* Display this data on the dashboard

**Comment by zipy124** [comment]
#1636 is very similar to this. I have just discovered that although we have a database model for the APICall object, we never actually use it. This means it appears we need to either start recording it using this model, or use a service like keen.
