### ISSUE TITLE
OAuth token endpoint complains about missing "Referer" header

### ISSUE THREAD

**Issue by mbellgb** [uclapi/uclapi#224]
When trying to obtain a token during the OAuth flow, my app receives an error complaining that the `Referer` header needs to be set, although this request is coming from a server, so it shouldn't be subject to CSRF checks.

I have an [example glitch app](https://glitch.com/edit/#!/ucl-assistant-auth?path=server.js:15:0) which is causing the error, and using the [grant](https://github.com/simov/grant) library to hide the complexity of dealing with OAuth. Also, the auth flow for my app is triggered by visiting [here](https://ucl-assistant-auth.glitch.me/connect/uclapi/).

My app then receives a HTTP page as an error message:

```json
{"content":{"error[\n<!DOCTYPE html>\n<html lang]":"\"en\">\n<head>\n  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n  <meta name=\"robots\" content=\"NONE,NOARCHIVE\">\n  <title>403 Forbidden</title>\n  <script src=\"/cdn-cgi/apps/head/MVm9YUQ9J9ItCAsh6xtCTgcZ8K0.js\"></script><style type=\"text/css\">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; background:#eee; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; margin-bottom:.4em; }\n    h1 span { font-size:60%; color:#666; font-weight:normal; }\n    #info { background:#f6f6f6; }\n    #info ul { margin: 0.5em 4em; }\n    #info p, #summary p { padding-top:10px; }\n    #summary { background: #ffc; }\n    #explanation { background:#eee; border-bottom: 0px none; }\n  </style>\n</head>\n<body>\n<div id=\"summary\">\n  <h1>Forbidden <span>(403)</span></h1>\n  <p>CSRF verification failed. Request aborted.</p>\n\n  <p>You are seeing this message because this HTTPS site requires a ","error[#39;Referer header]":"","error[#39; to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>\n  <p>If you have configured your browser to disable ]":"","error[#39;Referer]":"","error[#39; headers, please re-enable them, at least for this site, or for HTTPS connections, or for ]":"","error[#39;same-origin]":"","error[#39; requests.</p>\n\n\n</div>\n\n<div id]":"\"explanation\">\n  <p><small>More information is available with DEBUG=True.</small></p>\n</div>\n\n</body>\n</html>\n"},"error":""}
```

It didn't parse very well, but essentially is a page with this message:

```
CSRF verification failed. Request aborted. You are seeing this message because this HTTPS site requires a Referer header to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties. If you have configured your browser to disable Referer headers, please re-enable them, at least for this site, or for HTTPS connections, or for same-origin requests.
```

Either:

1) the API endpoint needs to be made CSRF-exempt (https://github.com/uclapi/uclapi/blob/master/backend/uclapi/oauth/views.py#L324)

2) my client's request isn't correctly formed, and the error message returned by the API is unhelpful.

**Comment by wilhelmklopp** [comment]
👋 Not entirely sure what the problem is here, but I get a feeling grant is doing something that isn't expected. I don't have much advice here besides suggesting to implement the OAuth flow by hand, which hopefully shouldn't be too hard. There is a [UCL API OAuth Glitch Demo app](https://glitch.com/~uclapi-oauth-demo), which should be of help :)


cc @ChristopherHammond13 for 👀

**Comment by mbellgb** [comment]
@wilhelmklopp Cheers for the reply!

I did originally try this with a completely different library (the OAuth2 strategy for `passport.js`) and had the same issue. I'll try implementing it myself though and will get back to you.

**Comment by mbellgb** [comment]
Looks like I got it working when I wrote my own code! Not sure what was throwing CSRF errors before though. For the record, you _are_ using v2 of the OAuth spec right?

I also see that there's no refresh tokens. Is that intentional?

**Comment by ChristopherHammond13** [comment]
Hey, apologies for not chiming in on this sooner.

We are using v2 of the spec but we intentionally did not implement refresh tokens. They make for a generally bad developer experience; all you end up doing is yet another request to just get a token that you would use in the same way anyway.

It's quite a limited subset, but it's nice and simple in that way so that you can implement it yourself and have full sight of what is going on. Do you know by chance what endpoint the library was trying to hit, and with what data?

**Comment by mbellgb** [comment]
I'm having a little dig around the source code for Grant, [this block of code](https://github.com/simov/grant/blob/master/lib/flow/oauth2.js#L57) suggests that they might be using form encoding to send the auth code, as well as using a POST request rather than a GET request. The latter I think is causing the issues

**Comment by ChristopherHammond13** [comment]
If we need to enable POST requests too, that should be fine. I'll create a GitHub issue for that and close that one, if that's ok?
