### ISSUE TITLE
/oauth/token Should Accept POST Requests

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#225]
Many OAuth 2.0 libraries seem to expect the `/oauth/token` endpoint to accept a POST request instead of a GET one. We should probably support this too if the RFC expects it.

**Comment by mbellgb** [comment]
https://ucl-assistant-auth.glitch.me

Updated this code to send a URL-encoded POST request instead of a GET request. Server returns CSRF error. Found the cause of my problems earlier! 😁

**Comment by ChristopherHammond13** [comment]
@mbellgb thank you so much for investigating this for us! I'll see if I can code up a quick solution to this now and get it into Staging. Would you might testing if I can?
