### ISSUE TITLE
OAuth down

### ISSUE THREAD

**Issue by balping** [uclapi/uclapi#2358]
Cannot use UCL API to log in with oauth. The error message below shows up before the system would ask for UCL username and password.

![error](https://user-images.githubusercontent.com/5840038/81368384-8ca9ba00-90e7-11ea-9e91-4ed4b620f297.png)

**Comment by Feverfew** [comment]
Hi @balping, this should now be fixed. Please close the issue if it is indeed fixed for you.

Thanks for reporting!

**Comment by zipy124** [comment]
@balping This has now been fixed, we apologize for the downtime and have put measures in place to stop this happening in the future!

**Comment by balping** [comment]
Works now, thank you!
