### ISSUE TITLE
Dashboard APIs

### ISSUE THREAD

**Issue by hueyy** [uclapi/uclapi#2413]
Write APIs to replace the Django template `{{ initialdata }}` embedding we currently do.

Authentication via `secure`, `HttpOnly` cookies, that are set server side

Need CRUD APIs for dashboard apps. There are already some, e.g. `/dashboard/api/create/` but these need to be modified to allow for authentication to expect JSON requests instead of `x-www-form-urlencoded` requests, and not to require a CSRF token.

**Comment by zipy124** [comment]
This relies on #2412 right? Since we should probably then use the Oauth token as validation for accessing the dashboard apis?
