### ISSUE TITLE
Right aligned arguments are hard to read

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#2445]
In the arguments section of our queries, the description is left aligned, but the argument name is right aligned, it is hard to associate them with each other.

![image](https://user-images.githubusercontent.com/6547350/83514910-64399380-a4cc-11ea-993a-e636e1cc0679.png)

**Comment by hueyy** [comment]
This is a regression probably caused by some accidental change to a core SCSS file. I raised it when it was on staging awhile ago. Will fix.

**Comment by hueyy** [comment]
@zipy124 

Just built and ran it locally in both development and production mode. The arguments are center-aligned. Apparently I fixed this regression back in https://github.com/uclapi/uclapi/commit/df9b0f2f85ebfe6396ffc3efda5e80b18903771f#diff-28e83c5ef566b4c313cdb203276af70eR315.

Perhaps try rebuilding and deploying the static assets again?

**Comment by zipy124** [comment]
This is fixed as suggested above, closing.
