### ISSUE TITLE
[BUG] Dashboard 500ing

### ISSUE THREAD

**Issue by tiferrei** [uclapi/uclapi#2600]
**Describe the bug**
Going to the dashboard (https://uclapi.com/dashboard) causes a 500 HTTP error. 

**To Reproduce**
1. Visit the dashboard, being already logged in with UCL SSO for the current browser session.
2. Get a 500 from the server.

**Expected behavior**
HTTP 200, maybe some API keys, not really sure, never got to the dashboard.

**Screenshots**
<img width="1552" alt="Screenshot 2020-07-23 at 23 51 37" src="https://user-images.githubusercontent.com/8849915/88346106-781cab80-cd3f-11ea-9ce5-e361a7453406.png">

**Additional context**
* I don't know if this would really affect anything, but I'm Staff at UCL, not a student. Don't know if maybe that affects the permissions.

**Comment by zipy124** [comment]
Hi @tiferrei , I wasn't able to replicate this personally, can you see if the issue still persists we think that may have been a server issue not a code bug. If it does still persist can you go to https://uclapi.com/Shibboleth.sso/Session and then tell us your details there, so we can investigate if it is to do with being Staff etc...

**Comment by tiferrei** [comment]
Ah all good now, thanks! Seems like it was something temporary. Closing as the issue has been resolved.
