### ISSUE TITLE
[Feature Request] Separate most popular methods by service

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#2814]
In the `/dashboard/api/analytics/methods` endpoint we list the most popular methods. This however is not useful without also knowing the service for example both `https://uclapi.com/timetable/data/modules` and `https://uclapi.com/timetable/data/courses/modules` are classed as the `modules` method` but they are different.

**Comment by ILW8** [comment]
It seems to me there are two ways to implement this. Either break compatibility with the results that are currently being returned by the api, or add a request parameter that toggles whether to group methods by services that defaults to False.
