### ISSUE TITLE
[BUG] Incomplete student headers

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#2827]
We should perodicatly check the database to check students information hasn't changed

**Comment by Feverfew** [comment]
In `oauth/views.py`, the `shibcallback()` function will create or update an existing user based on the data passed back from Shibboleth. However, when creating a user, some fields may be empty. There's scope to at least fill in the department name and names of a student via the students table. We may want to do something similar in `userdata()` as well.
