### ISSUE TITLE
LibCal API: Spaces - Write

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#2943]
A list of all API methods that are accessible with a token with the **Spaces - Write** (`sp_w`) scopes.

Whilst it is probably possible to use a scraper to automatically make bookings, we don't want to make it easier. Use of Google ReCaptcha V3 should be able to help us here:
https://django-rest-framework-recaptcha.readthedocs.io/

There will need to be some code that automatically manages the acquisition of an OAuth token, as those only last for an hour.

Action | URL | Method | Works
-- | -- | -- | --
Book 				spaces/seats in your system. | /space/reserve | POST | TBA
Cancel 				a space/seat booking. | /space/cancel/:id | POST | TBA

**Comment by hueyy** [comment]
If there isn't already some limit in LibCal, we could also impose limits on our side, perhaps up to 2h / person / day or something?

For privacy reasons and to avoid a dependency on an external API, we could also use [django-simple-captcha](https://github.com/mbi/django-simple-captcha).
