### ISSUE TITLE
Investigate Moodle API

### ISSUE THREAD

**Issue by shu8** [uclapi/uclapi#2999]
Moodle is open-source: https://github.com/moodle/moodle and they have an API for Web services: https://docs.moodle.org/dev/Web_services / https://docs.moodle.org/dev/Web_service_API_functions.

We might be able to investigate this a bit further and see if we can add it in UCL API?

Some use cases might be e.g. being able to list all Zoom URLs for your courses on a single page, or something similar?

**Comment by hueyy** [comment]
I looked briefly into this awhile back. I found it useful to look at a client implementation ([`moodleapp`](https://github.com/moodlehq/moodleapp) - it's in TS, but written like a Java app). There's also a useful `moodle-client` package on npm. 

I identified a few interesting endpoints:

```js

const moodle = require('moodle-client')

moodle.init({
	wwwroot: `https://moodle.ucl.ac.uk/`,

	// either authenticate with username & password or token

	// username: `your_username`,
	// password: `your_password`,

	// an user can obtain their token by calling
	// /login/token.php?username=USERNAME&password=PASSWORD&service=moodle_mobile_app
	// token: ``	
}).then(client => {
	client.call({
        // interesting functions which appear to work
		// wsfunction: "core_webservice_get_site_info",
		// wsfunction: "tool_mobile_get_config",
		// wsfunction: "core_message_get_contacts",5577
		// wsfunction: "core_group_get_course_user_groups";17m
		// wsfunction: "core_course_get_categories"
		wsfunction: "core_course_get_enrolled_courses_by_timeline_classification",
		args: {
			classification: "inprogress"
		}
	}).then(info => {
		console.log(info)
	})

	// get text, links, etc. for a particular module
	/*
	client.call({
		wsfunction: "core_course_get_contents",
		args: {
			courseid: 5577
		}
	}).then(info => {
		console.log(info)
	})
	*/
})

```

Some of the issues with this include:

- Institutions can choose which Moodle features to enable/disable and we don't have any proper way of finding out which moodle features work and which don't
- Some moodle features require an application API key (mostly the write ones) which we'll need to procure
- Moodle (or at least UCL's installation) doesn't seem to be integrated with Shibboleth, so if we don't have an API key with access to all users, we'll need end-users' usernames and passwords to make requests on their behalf which is less than ideal
