### ISSUE TITLE
[Feature Request] Utilize Sentry more effectively

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#3053]
We need to do the following:

1) Upgrade our plan to use Sentry for Education
2) Migrate from raven client (deprecated) to sentry client, enabling it also for our management commands that are tied to a crontab.
3) Enable Django (and Github?) integration.

**Comment by zipy124** [comment]
2 and 3 are doable. 1 we technically do not qualify as we aren't acting as students, teachers or researchers and so we will pay for it instead and get a buisness account maybe?

**Comment by greenfrogs** [comment]
Add:
- [ ] Gencache errors
- [ ] Add release information to Sentry (wait for #3114)
