### ISSUE TITLE
[BUG] AttributeError /dashboard/api/analytics/quota

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#3059]
**Describe the bug**
`AttributeError` `/dashboard/api/analytics/quota`
`NoneType` object has no attribute 'user'

**To Reproduce**
1.  `https://uclapi.com/dashboard/api/analytics/quota`
2.  HTTP 500

**Expected behavior**
Not crash

**Additional context**
`dashboard/api_applications.py:479`

**Comment by shu8** [comment]
note to self: it's when a token is in the valid format but does not exist (but this error doesn't happen on other endpoints with the same situation)
