### ISSUE TITLE
Inconsistent location addressing on timetable

### ISSUE THREAD

**Issue by mbellgb** [uclapi/uclapi#313]
It seems like the `location` value of timetabled events returned from the API is a little bit inconsistent. Here's a couple of examples of location objects I received from the API:

```json
"location": {
  "capacity": 123,
  "name": "Birkbeck Malet Street B36",
  "address": [
    "Malet Street",
    "London",
    ""
  ],
  "type": "CB",
  "site_name": "Birkbeck Malet Street"
}
```

```json
"location": {
  "capacity": 165,
  "name": "Royal National - Galleon B",
  "address": [
    "38-51 Bedford Way, Russel Square",
    "London",
    "WC1H 0DG"
  ],
  "type": "DB",
  "site_name": "Royal National Hotel"
}
```
```json
"location": {
  "address": [
    "Torrington Place",
    "London",
    "WC1E 7JE",
  ],
  "capacity": 91,
  "name": "Roberts Building 508",
  "site_name": "Roberts Building",
  "type": "CB",
}
```

```json
"location": {
  "address": [
    "1-19 Torrington Place",
    "London",
    "WC1E 7HB",
  ],
  "capacity": 120,
  "name": "Torrington (1-19) G12",
  "site_name": "Torrington Place, 1-19",
  "type": "CB",
},
```

Some of the addresses lack a postcode, some have spelling errors ("Russel Square", which isn't even part of the hotel's address), and some use "site_name" as the first address line, while others don't ("Torrington Place, 1-19", "Birkbeck Malet Street"). This makes geocoding addresses into coordinates _extremely_ difficult.

Ideally, it would be really handy if the coordinates of the locations were already provided in the API so I don't have to use a geocoding API, but at least if the addresses are consistent and correct, I can find them myself.

Thanks again! ✨

**Comment by ChristopherHammond13** [comment]
Hey! The co-ordinates are available in the /rooms endpoint. If it would make things easier I can set the coordinates to be delivered in the timetable API too? We also added a missing coordinate pair for siteid `RUS26` this morning in staging.

**Comment by ChristopherHammond13** [comment]
Unfortunately the address detail I'm not happy with comes from the central CMIS system we get data from so it's not possible for us to edit this without patching the incorrect data during the caching phase which would be a nasty hack.
For now, all the coordinate data we have will be returned once #298 is in prod, and it's in staging at the moment pending cleanup.
