### ISSUE TITLE
[Feature Request] User data - boolean over 18 field

### ISSUE THREAD

**Issue by MaxwellKeeble** [uclapi/uclapi#3159]
**Is your feature request related to a problem? Please describe.**

We have safeguarding responsibilities that mean we need to restrict access to certain areas to over 18s. 

**Describe the solution you'd like**

An is_over_18 flag on https://uclapi.com/docs/#oauth/user/data where the user is over 18 years of age.

**Describe alternatives you've considered (optional)**

Date of birth would provide too much identifiable personal information.

There is a risk a frequent requester could work out birthday if they happen to get a login before and then after the 18th birthday but that seems a minimal security risk as presumably they'd only ever get data when users log in and it's unlikely to be so frequent as to allow that.

** Other **

I know you may not have access via Shibboleth for this anyway, so it may well be impossible, but wanted it flagged regardless on the off chance.

**Comment by Feverfew** [comment]
I'm not aware of us having access to DoBs? Is this something that is given back in a typical Shibboleth response?

There's two ways this can work off the top of my head:
1. Only update the flag on Shibboleth response (as you've suggested). Again, as mentioned, two consecutive logins (around the birthday) can determine the DoB potentially and the data is more likely to go "stale" (I don't know what implications staleness has for you).
2. Always giving the correct value on `/oauth/userdata`. You can easily determine the DoB in this scenario, but at least you don't have to force the user through the Shibboleth workflow all the time. This can be mitigated by just replacing the flag with the DoB explitily, which the user will explicitly agree to (we can add this as a separate scope).

Alternatively, there might be a clever way, whilst also avoiding the trade-offs with either solution, if I thought about it a bit more.... no guarantees though.
