### ISSUE TITLE
[Feature Request] user data - middle name and surname

### ISSUE THREAD

**Issue by MaxwellKeeble** [uclapi/uclapi#3160]
**Is your feature request related to a problem? Please describe.**

User data via OAuth currently includes only full name and given name. We would like surname for certain uses on our site. 

Surname cannot be derived reliably from full name because e.g. in a Spanish name the last two words separated by a space are the surname, while for an English name that's likely the middle name and last name. 

**Describe the solution you'd like**

A separate field each for middle name and surname.

**Describe alternatives you've considered (optional)**

Otherwise we may need to prompt users when they first log in for this information. 

**Other**

As with other request, this may be limited by Shibboleth itself.

**Comment by Feverfew** [comment]
We have a patch to add surnames here [here](https://github.com/uclapi/uclapi/pull/3099/files#diff-ff0caa4230fd58a3c8a80c17d7af95b21a506367a0c42d6bf1b957ad63818a70R23) (although I didn't add these additional fields to the `/oauth/userdata` response, I'll add that to my TODO). This isn't in production yet, but please let us know of your time constraints and we'll speed up the inclusion of that patch.

However, even when this patch goes in, to get the surname the user will have to go through the Shibboleth process again, which can happen under 2 scenarios:
1. Logging into `uclapi.com`
2. An app going through the OAuth workflow (i.e., `/oauth/authorise`).

You can't assume either of these have happened (although they might have), so if having a surname is paramount, you can force the user through the the OAuth workflow again to get the surname, as that in turn will force them through Shibboleth.

I've never seen Shibboleth return middle names separately, is this something that you've received on Shibboleth before?

I'm not entirely sure, but you may be able to split the name into "first name" (i.e. `given_name`) and "other names" (`full_name` but with `given_name` taken out), if that's good enough?

**Comment by greenfrogs** [comment]
Surname in OAuth is now deployed to production (called `sn`)
