### ISSUE TITLE
[BUG] Incomplete headers error when logging in through the "Settings" button

### ISSUE THREAD

**Issue by ILW8** [uclapi/uclapi#3235]
**Describe the bug**
When not logged in, clicking the Settings button on the home page and logging in through UCL SSO results in the incomplete headers error page.
Opening a new tab and clicking on the Marketplace button correctly completes login.

**To Reproduce**
1. Log out of UCLAPI
2. Click on the Settings button on  the home page
3. Log in
4. Observe the error message

**Expected behavior**
Logs the user in normally.

**Screenshots**
![Screenshot](https://drive.google.com/uc?id=1s8kX2qDtbar5GsRv2qV7yfYXilnkm9_8)

**Additional context**
Logging in via the Settings button creates this issue 100% of the time. Logging in via the marketplace button does not exhibit the same behavior.

**Comment by Feverfew** [comment]
Same as #3072 but this has slightly more detail so I'll leave this up.

`staging.ninja` has additional debugging info, which shows that there are no fields present at all :/, so this is a setup issue, unlikely to be something with the code
