### ISSUE TITLE
[Feature Request] Github action to deploy to prod

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#3379]
Currently deploying to staging is automated. It is trivial to change that action to also deploy to production. This would then allow all members of the team to upgrade to production when ready, removing any manual elements to the process that currently exist, and get rid of the need to generate statics on someone's workstation.

**Comment by shu8** [comment]
Just adding to this -- this would probably work together with the steps mentioned in https://github.com/uclapi/uclapi/issues/3056#issuecomment-825815687 (if we decide on that route), where when we create a GitHub release with a version number it would deploy to production automatically!

**Comment by greenfrogs** [comment]
When we have release versions we should also add Sentry release integration!!!!
