### ISSUE TITLE
[BUG] 502 Bad Gateway on /roombookings/equipment 

### ISSUE THREAD

**Issue by shu8** [uclapi/uclapi#3576]
**Describe the bug**
`https://uclapi.com/roombookings/equipment?roomid=106D&siteid=088&token=YOUR_TOKEN_HERE` times out.

**To Reproduce**
1. Request endpoint with these parameters
2. Get 502 Bad Gateway after around 30 seconds

**Expected behavior**
A JSON response

**Additional context**
It looks like it's all rooms/sites, I tried with a few different ones.

**Comment by greenfrogs** [comment]
This is fixed on staging and will be closed on the next release.
