### ISSUE TITLE
Add setup to README

### ISSUE THREAD

**Issue by HugoDF** [uclapi/uclapi#44]
This person failed to add a description :( or setup instructions to the README

**Comment by ChristopherHammond13** [comment]
Nothing has changed on this issue since it was raised so I'm not really sure what was wanted, so I'm closing it.

**Comment by ChristopherHammond13** [comment]
#85 should clarify some of this. It also explains why the API cannot be hosted just by anybody: Oracle access credentials are required for all requests. Until we have some dummy Oracle data it is not possible for anybody outside the team to have a fully functioning dev environment right now. However, aside from actually making requests, it should still be possible for anybody to build and run the API locally now.
