### ISSUE TITLE
Apple Swift Wrapper

### ISSUE THREAD

**Issue by tiferrei** [uclapi/uclapi#45]
Hello there,

my name is Tiago, I am currently taking my GCSEs but sometimes help around with UCL Computer Science events. I am also very keen in Swift development and am familiar with HTTP APIs. I have helped to develop fairly popular GitHub and GitLab API wrappers for Swift, the aid of the wrappers is to create a framework that handles all API requests, so that the developer can forget about requests, formatting, parsing, etc, and with one line do a request and receive the results fully parsed in object properties.

I wanted to develop a wrapper for the UCL API, this would increase drastically the API's usage on any Apple platform. I would like to do this as one of my side-projects mainly because I would love to do a Computer Science degree at UCL, and coding something useful for UCL students would really be meaningful to me.

I have however, faced a problem. I am not able to get an API key, as I am not an UCL student, so no API testing, which makes all the development painfully slow, as I can't automate CI or Unit tests, and rely on other people to test the API for me.
Is there any way that a student not currently at UCL can get an API key?

Thank you,
Tiago

PS: The other frameworks are [octokit.swift](https://github.com/nerdishbynature/octokit.swift) and [TanukiKit](https://github.com/nerdishbynature/TanukiKit), just to give some examples of how it would look like.

**Comment by xoneco** [comment]
Hi Thiago,

Extremely impressive what you've already worked on and I really appreciate the enthusiasm! I am super excited about this. Efforts like this are exactly what we need to make the API awesome.

I've asked ISD whether we're able to give access to the API to non-ucl students, and unfortunately for the time being the answer is no. So while I cannot stop anybody at UCL from giving you an API key, it's not something we're currently in a position to support officially.

This kind of sucks and as you've just shown there's a lot of value that can be brought to UCL systems even by folks not at UCL (at leasy not yet 😉 ). We're now looking into how we can improve this and open up access to external developers as well, but this might take a while.

Wil

**Comment by tiferrei** [comment]
Thanks, I completely understand that! Ok let's do it like this, I'll rely on the docs for expected output, parsing will be done exactly like the example json responses, so you guys just be sure to keep it up-to-date, and as long as you keep updating your docs, I'll be able to update UCLKit. Sounds like a plan?

**Comment by tiferrei** [comment]
One last thing, is there any way I can be added to the slack team? Again, no UCL domain email...

**Comment by xoneco** [comment]
Yup, let's give it a shot! 💯
Keeping the docs up to date is a top priority for us. :D
