### ISSUE TITLE
JavaScript Wrapper

### ISSUE THREAD

**Issue by HugoDF** [uclapi/uclapi#49]
I have created an API wrapper for JavaScript.
https://github.com/HugoDF/uclapi-javascript
It works in the browser (or any environment that implement XHR) and in Node.
Tests and documentation to come.

**Comment by ChristopherHammond13** [comment]
I feel like this "issue" should probably be closed

**Comment by wilhelmklopp** [comment]
As mentioned in DM, thanks a lot for creating this @HugoDF ! 💯
