### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by adamfaliq42** [uclapi/uclapi#502]
In the documentation page, https://uclapi.com/docs/#workspaces/images/map/live, the author said that the required keys are `token`, `survey_id` and `map_id`. However, I received `image_id` error. 

The GET request requires `image_id` query, which is the ID of the map's image. Others are optional.

**Comment by ChristopherHammond13** [comment]
Thanks for that! Well spotted. I'll get a fix for this sorted after my exams :)

**Comment by ChristopherHammond13** [comment]
I just checked the documentation and it looks right.

To get the [static map image ](https://github.com/uclapi/uclapi/blob/master/backend/uclapi/workspaces/views.py#L34) you use the `image_id`, and to get a [live map image](https://github.com/uclapi/uclapi/blob/master/backend/uclapi/workspaces/views.py#L256) you use `survey_id` and `map_id`.

If I've still missed something do feel free to re-open the issue. Thanks for the report!
