### ISSUE TITLE
Remove opbeat

### ISSUE THREAD

**Issue by wilhelmklopp** [uclapi/uclapi#544]
Opbeat is no longer a thing, so we should remove it and replace it with something else? Maybe double down on Sentry and integrate that more tightly

https://github.com/uclapi/uclapi/blob/81b90305f9316b020664b32c2436e27ab957e8a7/backend/uclapi/requirements.txt#L33

**Comment by ChristopherHammond13** [comment]
I was literally about to come to this issues page to open the exact same issue. BRAIN SYNC.
