### ISSUE TITLE
Docs incomplete

### ISSUE THREAD

**Issue by balping** [uclapi/uclapi#746]
https://github.com/uclapi/uclapi/blob/8e1af7bb337e1e21a3f79e69c7dddd5698e502a8/frontend/src/components/documentation/Meta/VersionInformation.jsx#L24

There's nothing on the right hand side

**Comment by ChristopherHammond13** [comment]
Versioning is mostly deprecated at this point. We should remove that stuff from the docs completely.

**Comment by Faiz** [comment]
Are we removing versioning completely? Or just out of the docs for now?

**Comment by ChristopherHammond13** [comment]
@Faiz it should probably come out of the docs for now at least.

**Comment by zipy124** [comment]
@ChristopherHammond13 Update on this?
