### ISSUE TITLE
Feature Request: Extend /search to rooms.

### ISSUE THREAD

**Issue by tiferrei** [uclapi/uclapi#779]
Hey everyone!

Currently `/search` works with `GET People`, I was wondering if there were any plans to make a `/search/roombookings` endpoint? This would be super useful, as right now I kinda have to ask users what sort of query they're entering, i.e. site name, site id, room name, classification, etc.
It would be cool to reduce this to a simple search field and just listing all occurrences. 

Does this sound viable?

Thanks,
Tiago

**Comment by ChristopherHammond13** [comment]
@tiferrei Apologies for not responding to this! It's been a hectic month and I'm catching up now.

One option could be to use `/rooms` to get a list of rooms, then you can auto-fill the Site ID / Room ID from this. What's the use case exactly so I can try and draw something up?

**Comment by tiferrei** [comment]
Well I just wanted to build something almost like a google search for the rooms. Where you could enter anything from a specific room ID, to an address, capacity, etc.

**Comment by ChristopherHammond13** [comment]
Best solution reasonable has been merged in #984 
To have 'OR' instead of 'AND', best answer right now is to make multiple related requests back to back or in parallel, and merge those results together.
