### ISSUE TITLE
Implement HiRedis

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#884]
At the moment we are using the Redis Py default which is the `PythonParser`. By installing HiRedis we may be able to take advantage of speed improvements provided by the C bindings.

**Comment by zipy124** [comment]
Isn't HiRedis the defualt parser as long as its installed? In the Redis-Py docs it says "By default, redis-py will attempt to use the HiredisParser if you have the hiredis module installed and will fallback to the PythonParser otherwise."

**Comment by ChristopherHammond13** [comment]
@zipy124 Yeah that should be true, and an easy one. I'm not sure how we can test that that's true, but if we add the requirement and the test suite passes we should be ok. Is HiRedis compatible with the latest version of redis-py?
Assigning you your first issue!
