### ISSUE TITLE
Kill Cron

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#914]
At the moment, we are using cron jobs to do our caching operations. We need to replace this with something more reliable.

The Workspaces API might be doable with AWS Lambda as even the full cache takes under 15 minutes. Gencache work will require up to 20 minutes, and therefore a tool such as AWS Batch might be more appropriate. 

If keeping cron jobs does turn out to be the most reliable way of doing this, we need to be able to monitor the cron server and automatically restart it if something goes wrong, as stale data makes us irrelevant.

**Comment by Feverfew** [comment]
AWS Lambda is good for saving cost. But a more robust solution would be systemd services that restart on exit. Which means our cronbox is constantly used, and our gencache runs as soon as the previous one finished.

**Comment by zipy124** [comment]
@Feverfew Not sure this is the right solution actually, given how pricing works for the t2/3 instances we use on AWS when cpu utilization is at 100% (burst credits).

**Comment by ChristopherHammond13** [comment]
Step 1) Move to Kubernetes
Step 2) Use Kubernetes Cron
Step 3) ???
Step 4) Semi-Profit

**Comment by Feverfew** [comment]
Seeming as we use Ubuntu for production, systemd may be "cleaner" than using Cron

**Comment by ILW8** [comment]
> Step 1) Move to Kubernetes
> Step 2) Use Kubernetes Cron
> Step 3) ???
> Step 4) Semi-Profit

We've done it! Not quite k8s, but it's nearly the same!

**Comment by greenfrogs** [comment]
In only 2 years and 8 months

**Comment by greenfrogs** [comment]
I am very happy to say that this has now been pushed to production!


> Cron is dead. Cron remains dead. And we have killed him.
