### ISSUE TITLE
Automation of S3 Statics

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#915]
At the moment, statics are built locally and deployed to S3 by the developer. We need a way to better test the build of statics and roll them out to S3 at the same time that code is rolled out.

Ideally, the version of each static should be requested in code so that the version corresponding to the commit version of UCL API is served. This will require some logic in Django, as well as proper integration with Travis.

**Comment by zipy124** [comment]
Pushes to master now builds the statics and uploads.
