### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#919]
I already set up cachet on status.uclapi.com but I shut it down because it needed manually maintaining. 

We should have Cachet set up on CaptainDuckDuck, our Apps Platform (apps.uclapi.com), and configure minutely checking of all the services so that we can quickly identify (and publish) when something is down.

We should also have this status page easily accessible in the event that any part of the main system goes down.

**Comment by zipy124** [comment]
Cachet has been set-up on caprover. We also have a PR open for specific monitoring of cachet and teams integration.
