### ISSUE TITLE
Python 3.7 Migration

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#921]
We currently use Python 3.6 in production. There is no reason for us not to use 3.7, and indeed we develop with it, but we should ensure that all of our tooling is happy with 3.7.

**Comment by zipy124** [comment]
Starting today staging will be upgraded to python 3.7. If issues present themselves then we will revert, if not we can do the same to production.

**Comment by zipy124** [comment]
We have a blocker on https://github.com/eventlet/eventlet/issues/526 . eventlet does not work with python 3.7 due to changes in the python ssl library between 3.6 and 3.7.

**Comment by zipy124** [comment]
Switching to gevent will fix this, making the necessary changes now and then will run tests to ensure this doesn't break anything.

**Comment by zipy124** [comment]
Testing has been completed and both staging and prod have been migrated.

**Comment by zipy124** [comment]
It is not possible to move back to eventlet as the bug above has been fixed, however gevent actually has better performance.
