### ISSUE TITLE
Create our own apt repository

### ISSUE THREAD

**Issue by Feverfew** [uclapi/uclapi#950]
Several packages that we need for our production environment are outdated for us, i.e. nginx and shibboleth. If we create our own repository we can clone and build the packages we need and easily install via our repository. We'll need to address how we can guarantee security, in particular, removing the possibility of a rogue actor tampering with the repository and to be able to confirm that what we have installed is only from that repository.

**Comment by ChristopherHammond13** [comment]
Right now I have worked around this with https://github.com/uclapi/nginx-build
