### ISSUE TITLE
Properly explain the types of tokens to developers

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#956]
As explained in #864, it is unclear to new developers that there are general tokens and OAuth tokens that often hugely overlap in application.

We should update both the documentation and the dashboard to assist developers in knowing which tokens they can use and where.

**Comment by zipy124** [comment]
Is this done? in oauth workflow in the docs we say ```Note: OAuth tokens and general API tokes are different. Whilst general API tokens can be used for all non-personal, generic data (such as room bookings), OAuth tokens must be used with an app's `client_secret` in order to retrieve personal data for a user. To make things easier, you can use personal OAuth tokens in place of general tokens once a user has logged into your app to retrieve generic data too.```

**Comment by zipy124** [comment]
Closed as of PR: #1068
