### ISSUE TITLE
Compress Frontend Assets

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#963]
- JPG all the things
- gzip all the things
- Make sure S3 is happy to serve gzipped content

**Comment by zipy124** [comment]
In the meantime images have been compressed as small as png will allow. not sure JPG is required tbh. gzip would be good though. ref: #1058

**Comment by hueyy** [comment]
Might I suggest we use [Cloudinary](https://cloudinary.com) for compressing and serving images? That way we don't need to maintain and tweak an image optimisation solution, and we can easily serve assets based on the capabilities of the browser (e.g. WebP to Chrome and JPEG-XR to IE).

There's a free tier (25GB of storage) which seems more than sufficient for our needs.

**Comment by hueyy** [comment]
Resolved in #1347
